WIP: Sanity check model configurations
twosixlabs/armory pull request #875
Opened 2020-10-30 14:51 UTC by kevinmerchant

Closes #753 

To run/test, run the following command using one of the example configurations in the scenario_configs folder:
`python -m armory run <path_to_scenario_config_json> --validate-config`

2020-11-02 23:26 UTC, davidslater commented
`armory/utils` seems like an odd place to put the `test_config` folder. How about creating a higher level folder like `armory/validation` or `armory/validate` or `armory/verify` or `armory/checks` and putting it there?

2020-11-03 13:53 UTC, kevinmerchant commented
Moved to `armory/validation`

2020-11-03 16:06 UTC, lcadalzo requested changes
Generate arbitrary ground truth for object detectors, rather than using the predicted output as ground truth

2020-11-03 16:15 UTC, lcadalzo commented on armory/validation/test_config/test_model.py
> +        if hasattr(model, "nb_classes"):
This is minor, but `test_output.shape` will fail when `test_output` is not a numpy array, which is the case for object detection. I suppose the ART object detectors don't have a `nb_classes` attribute, so this conditional block likely won't be reached, but there would be nothing stopping a user from adding a `nb_classes` attribute in their custom detector

2020-11-03 23:53 UTC, kevinmerchant commented
Modified the test ground truth generation to create a set of bounding boxes for object detector gradient testing.

2020-11-04 16:09 UTC, lcadalzo approved these changes

2020-11-04 16:12 UTC, lcadalzo commented
LGTM but I think it'd be useful to include the use/purpose of `--validate-config` in the documentation

2020-11-04 20:34 UTC, merged