WIP Add type annotations to baseline models
twosixlabs/armory pull request #885
Opened 2020-11-04 16:26 UTC by ng390

Add type annotations to baseline models. Still adding docstrings, but want to run CI testing on the type annotations.

2020-11-04 23:36 UTC, davidslater approved these changes
All the checks passed.

2020-11-05 19:04 UTC, adamj26 requested changes

2020-11-05 19:04 UTC, adamj26 commented on armory/baseline_models/keras/micronnet_gtsrb.py
> +def get_art_model(model_kwargs: dict, wrapper_kwargs: dict, weights_path: str = None):
Shouldn't this be `Optional[str]`, since the default is `None`?

2020-11-05 19:04 UTC, adamj26 commented on armory/baseline_models/keras/mnist.py
> +def get_art_model(model_kwargs: dict, wrapper_kwargs: dict, weights_path: str = None):
`weights_path: Optional[str]`?

2020-11-05 19:04 UTC, adamj26 commented on armory/baseline_models/keras/resnet50.py
> +    model_kwargs: dict, wrapper_kwargs: str, weights_path: Optional[str] = None
`wrapper_kwargs: dict`?

2020-11-05 19:24 UTC, ng390 commented
@adamj26 Ready for another round of review.

2020-11-05 19:34 UTC, adamj26 approved these changes

2020-11-05 19:35 UTC, merged